//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTourTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhTour
    {
        public string id_anh { get; set; }
        public string id_tourmau { get; set; }
        public string TenAnh { get; set; }
        public string DuongDan1 { get; set; }
        public string DuongDan2 { get; set; }
        public string DuongDan3 { get; set; }
        public string DuongDan4 { get; set; }
        public string DuongDan5 { get; set; }
        public string DuongDan6 { get; set; }
        public string DuongDan7 { get; set; }
    
        public virtual TourMau TourMau { get; set; }
    }
}
