//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTourTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ThongTinKhachHang = new HashSet<ThongTinKhachHang>();
        }
    
        public string id_hoadon { get; set; }
        public string id_tour { get; set; }
        public string Gmail { get; set; }
        public string DichVu { get; set; }
        public Nullable<int> SoLuongHanhKhach { get; set; }
        public string Ten_LienLac { get; set; }
        public string SDT_LL { get; set; }
        public string TenNganHang { get; set; }
        public Nullable<int> TrangThaiDonHang { get; set; }
        public string HinhThucThanhToan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinKhachHang> ThongTinKhachHang { get; set; }
    }
}
