//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTourTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDong
    {
        public string id_hoatdong { get; set; }
        public string id_lichtrinh { get; set; }
        public string TenHoatDong { get; set; }
        public string MoTa { get; set; }
    
        public virtual LichTrinhTheoNgay LichTrinhTheoNgay { get; set; }
    }
}
