//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTourTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinLuuY
    {
        public string id_thongtinluuy { get; set; }
        public string id_tourmau { get; set; }
        public string TenThongTin { get; set; }
        public string MoTa { get; set; }
    
        public virtual TourMau TourMau { get; set; }
    }
}
