//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTourTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public string id_tour { get; set; }
        public string id_tourmau { get; set; }
        public string id_hdv { get; set; }
        public string TenTour { get; set; }
        public System.DateTime KhoiHanh { get; set; }
        public System.DateTime TapTrung { get; set; }
        public string ThoiGian { get; set; }
        public string NoiKhoiHanh { get; set; }
        public int SoLuongToiDa { get; set; }
        public decimal GiaNguoiLon { get; set; }
        public decimal GiaTreEm { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public string Avata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual HuongDanVien HuongDanVien { get; set; }
        public virtual TourMau TourMau { get; set; }
    }
}
