//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTourTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourMau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourMau()
        {
            this.AnhTour = new HashSet<AnhTour>();
            this.LichTrinhTheoNgay = new HashSet<LichTrinhTheoNgay>();
            this.Tour = new HashSet<Tour>();
            this.ThongTinLuuY = new HashSet<ThongTinLuuY>();
            this.DiaDiem = new HashSet<DiaDiem>();
        }
    
        public string id_tourmau { get; set; }
        public string TenTourMau { get; set; }
        public string ThoiGian { get; set; }
        public string PhuongTienDiChuyen { get; set; }
        public string DiemThamQuan { get; set; }
        public string AmThuc { get; set; }
        public string KhachSan { get; set; }
        public string ThoiGianLyTuong { get; set; }
        public string DoiTuongThichHop { get; set; }
        public string UuDai { get; set; }
        public string MoTaTourMau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhTour> AnhTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinhTheoNgay> LichTrinhTheoNgay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinLuuY> ThongTinLuuY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaDiem> DiaDiem { get; set; }
    }
}
